-- Bulk ATS config update — generated 2026-03-07
-- Run this in Supabase SQL Editor

UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'kroo'                         WHERE trading_name ILIKE '%kroo%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'knowledgebrief'               WHERE trading_name ILIKE '%knowledgebrief%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'King_External_Careers'        WHERE trading_name ILIKE '%king%' AND trading_name ILIKE '%activision%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'keyfactorinc'                 WHERE trading_name ILIKE '%keyfactor%';
UPDATE companies SET ats_provider = 'personio',       ats_board_token = 'katkin'                       WHERE trading_name ILIKE '%katkin%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'kadmos3'                      WHERE trading_name ILIKE '%kadmos%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'jupiter_careers'              WHERE trading_name ILIKE '%jupiter asset%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'jungheinrich'                 WHERE trading_name ILIKE '%jungheinrich%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'jensenhughes'                 WHERE trading_name ILIKE '%jensen hughes%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'jajafinance'                  WHERE trading_name ILIKE '%jaja%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'jdsports'                     WHERE trading_name ILIKE '%jd sports%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'isomorphiclabs'               WHERE trading_name ILIKE '%isomorphic%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = 'intropic'                     WHERE trading_name ILIKE '%intropic%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'intradiem'                    WHERE trading_name ILIKE '%intradiem%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'insuranceinsider'             WHERE trading_name ILIKE '%insurance insider%';
UPDATE companies SET ats_provider = 'smartrecruiters',ats_board_token = 'InformaGroupPlc'              WHERE trading_name ILIKE '%informa%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'iceye'                        WHERE trading_name ILIKE '%iceye%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'masabi'                       WHERE trading_name ILIKE '%masabi%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'loopme'                       WHERE trading_name ILIKE '%loopme%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = 'loopreturns'                  WHERE trading_name ILIKE '%loop returns%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'livescore9'                   WHERE trading_name ILIKE '%livescore%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'lindushealth'                 WHERE trading_name ILIKE '%lindus%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'Lime'                         WHERE trading_name ILIKE '%lime%' AND trading_name NOT ILIKE '%sublim%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'lightspeedhq'                 WHERE trading_name ILIKE '%lightspeed%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'lighthousegames'              WHERE trading_name ILIKE '%lighthouse games%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = 'economicmodeling'             WHERE trading_name ILIKE '%emsi%' OR trading_name ILIKE '%economic model%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Liberty_Global_Careers'       WHERE trading_name ILIKE '%liberty global%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'External'                     WHERE trading_name ILIKE '%leidos%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'legl'                         WHERE trading_name ILIKE '%legl%' OR trading_name ILIKE '%l.e.g.l%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'lantum'                       WHERE trading_name ILIKE '%lantum%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Landseccareers'               WHERE trading_name ILIKE '%landsec%';
UPDATE companies SET ats_provider = 'icims',          ats_board_token = 'lslps'                        WHERE trading_name ILIKE '%lsl property%';
UPDATE companies SET ats_provider = 'personio',       ats_board_token = 'liganova-mash'                WHERE trading_name ILIKE '%liganova%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'CMC_Markets_Careers'          WHERE trading_name ILIKE '%cmc markets%';
UPDATE companies SET ats_provider = 'smartrecruiters',ats_board_token = 'Versant3'                     WHERE trading_name ILIKE '%versant%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'cur8earth'                    WHERE trading_name ILIKE '%cur8%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'cambridgeconsultantslimited'  WHERE trading_name ILIKE '%cambridge consultant%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'CanadaGooseCareers'           WHERE trading_name ILIKE '%canada goose%';
UPDATE companies SET ats_provider = 'smartrecruiters',ats_board_token = 'Canva'                        WHERE trading_name ILIKE '%canva%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'carmoola-1'                   WHERE trading_name ILIKE '%carmoola%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'carnallfarrar'                WHERE trading_name ILIKE '%carnall farrar%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'jobs'                         WHERE trading_name ILIKE '%carrier%' AND trading_name NOT ILIKE '%financial%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Centrica'                     WHERE trading_name ILIKE '%centrica%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'chainalysis-careers'          WHERE trading_name ILIKE '%chainalysis%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'charlotte-tilbury'            WHERE trading_name ILIKE '%charlotte tilbury%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'CheckoutCareers'              WHERE trading_name ILIKE '%checkout.com%' OR trading_name ILIKE '%checkout com%';
UPDATE companies SET ats_provider = 'pinpoint',       ats_board_token = 'chetwood-bank'                WHERE trading_name ILIKE '%chetwood%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Cisco_Careers'                WHERE trading_name ILIKE '%cisco%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'clearbank'                    WHERE trading_name ILIKE '%clearbank%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'clearscoretechnologylimited'  WHERE trading_name ILIKE '%clearscore%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'cledara'                      WHERE trading_name ILIKE '%cledara%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = 'coupa'                        WHERE trading_name ILIKE '%coupa%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'costello-medical'             WHERE trading_name ILIKE '%costello medical%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'copperco'                     WHERE trading_name ILIKE '%copper%' AND trading_name NOT ILIKE '%copperclay%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'corepowerenergy'              WHERE trading_name ILIKE '%core power%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'cytora.com'                   WHERE trading_name ILIKE '%cytora%';
UPDATE companies SET ats_provider = 'breezyhr',       ats_board_token = 'disperse'                     WHERE trading_name ILIKE '%disperse%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'diligentcorporation'          WHERE trading_name ILIKE '%diligent%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'digital-catapult'             WHERE trading_name ILIKE '%digital catapult%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'deployflow'                   WHERE trading_name ILIKE '%deployflow%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Deluxe_External'              WHERE trading_name ILIKE '%deluxe%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'definelycareers'              WHERE trading_name ILIKE '%definely%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'deep-science-ventures'        WHERE trading_name ILIKE '%deep science%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'Deel'                         WHERE trading_name ILIKE '%deel%';
UPDATE companies SET ats_provider = 'jobvite',        ats_board_token = 'double-negative-visual-effects' WHERE trading_name ILIKE '%dneg%' OR trading_name ILIKE '%double negative%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'dicefm-careers'               WHERE trading_name ILIKE '%dice%' AND trading_name NOT ILIKE '%syndicep%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'hebbia'                       WHERE trading_name ILIKE '%hebbia%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'healthhero'                   WHERE trading_name ILIKE '%healthhero%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'Healthtech-1'                 WHERE trading_name ILIKE '%healthtech%' AND trading_name NOT ILIKE '%nhs%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'harvey'                       WHERE trading_name ILIKE '%harvey%' AND trading_name NOT ILIKE '%nash%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Harrods_External1'            WHERE trading_name ILIKE '%harrods%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'hadean'                       WHERE trading_name ILIKE '%hadean%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'hicx-solutions'               WHERE trading_name ILIKE '%hicx%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'hcacareers'                   WHERE trading_name ILIKE '%hca healthcare%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'CareersGrantThornton'         WHERE trading_name ILIKE '%grant thornton%';
UPDATE companies SET ats_provider = 'smartrecruiters',ats_board_token = 'Gousto1'                      WHERE trading_name ILIKE '%gousto%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'goji-investments-1'           WHERE trading_name ILIKE '%goji%';
UPDATE companies SET ats_provider = 'personio',       ats_board_token = 'glyphic'                      WHERE trading_name ILIKE '%glyphic%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'gssukserviceslimited'         WHERE trading_name ILIKE '%gss uk%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'gileadcareers'                WHERE trading_name ILIKE '%gilead%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'gvi'                          WHERE trading_name ILIKE '%gvi%';
UPDATE companies SET ats_provider = 'hibob',          ats_board_token = 'generalindex'                 WHERE trading_name ILIKE '%general index%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'generalassembly'              WHERE trading_name ILIKE '%general assembly%';
UPDATE companies SET ats_provider = 'successfactors', ats_board_token = 'gates'                        WHERE trading_name ILIKE '%gates%' AND trading_name NOT ILIKE '%bill%';
UPDATE companies SET ats_provider = 'oracle_cloud',   ats_board_token = 'intuit'                       WHERE trading_name ILIKE '%intuit%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'hutch'                        WHERE trading_name ILIKE '%hutch%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'holisticai'                   WHERE trading_name ILIKE '%holistic ai%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'hivedhq'                      WHERE trading_name ILIKE '%hived%';
UPDATE companies SET ats_provider = 'smartrecruiters',ats_board_token = 'HitachiSolutions'             WHERE trading_name ILIKE '%hitachi solutions%';
UPDATE companies SET ats_provider = 'icims',          ats_board_token = 'hines'                        WHERE trading_name ILIKE '%hines%';
UPDATE companies SET ats_provider = 'successfactors', ats_board_token = 'hikma'                        WHERE trading_name ILIKE '%hikma%';

-- Note: the following providers don't have fetchers yet (they'll be skipped in sync):
-- Phenom (Haleon), LinkedIn Jobs (Habito, Genflow), IBM ATS (IBM), Custom ATS (~6 companies), Jobvite (DNEG)
-- UPDATE companies SET ats_provider = 'phenom',    ats_board_token = 'haleon'              WHERE trading_name ILIKE '%haleon%';
-- UPDATE companies SET ats_provider = 'linkedin',  ats_board_token = '4375212715'          WHERE trading_name ILIKE '%habito%';
-- UPDATE companies SET ats_provider = 'linkedin',  ats_board_token = '4368655542'          WHERE trading_name ILIKE '%genflow%';
-- UPDATE companies SET ats_provider = 'ibm',       ats_board_token = 'ibm'                 WHERE trading_name ILIKE '%ibm%';
-- UPDATE companies SET ats_provider = 'custom_ats',ats_board_token = 'hansonwadegroup'     WHERE trading_name ILIKE '%hanson wade%';
-- UPDATE companies SET ats_provider = 'custom_ats',ats_board_token = 'joinhandshake'       WHERE trading_name ILIKE '%handshake%';
-- UPDATE companies SET ats_provider = 'custom_ats',ats_board_token = 'isio'                WHERE trading_name ILIKE '%isio%';
-- UPDATE companies SET ats_provider = 'custom_ats',ats_board_token = 'infobric'            WHERE trading_name ILIKE '%infobric%';
-- UPDATE companies SET ats_provider = 'custom_ats',ats_board_token = 'home-made'           WHERE trading_name ILIKE '%home made%';

-- ─── Batch 2 ─────────────────────────────────────────────────────────────────

UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'accenturecareers'             WHERE trading_name ILIKE '%accenture%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'Ferovinum'                    WHERE trading_name ILIKE '%ferovinum%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'mazedesign'                   WHERE trading_name ILIKE '%maze design%' OR trading_name ILIKE '%maze.design%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'lilt-corporate'               WHERE trading_name ILIKE '%lilt%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'Perk'                         WHERE trading_name ILIKE '%perk%' AND char_length(trading_name) < 10;
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'agreena'                      WHERE trading_name ILIKE '%agreena%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'raycast'                      WHERE trading_name ILIKE '%raycast%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'gaiafamily'                   WHERE trading_name ILIKE '%gaia family%' OR trading_name ILIKE '%gaiafamily%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'relationrx'                   WHERE trading_name ILIKE '%relationrx%' OR trading_name ILIKE '%relation rx%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'appier'                       WHERE trading_name ILIKE '%appier%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'deepmind'                     WHERE trading_name ILIKE '%deepmind%' OR trading_name ILIKE '%deep mind%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'CoStarCareers'                WHERE trading_name ILIKE '%costar%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = 'moneyboxapp'                  WHERE trading_name ILIKE '%moneybox%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = 'CordTechnologies'             WHERE trading_name ILIKE '%cord technolog%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = 'vivacitylabs'                 WHERE trading_name ILIKE '%vivacity%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = 'octoenergy'                   WHERE trading_name ILIKE '%octopus energy%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'antaretechnology'             WHERE trading_name ILIKE '%antare%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'praktika'                     WHERE trading_name ILIKE '%praktika%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'hybridairvehicleslimited'     WHERE trading_name ILIKE '%hybrid air vehicle%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'breathebatterytechnologies'   WHERE trading_name ILIKE '%breathe battery%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'advancedelectricmachines'     WHERE trading_name ILIKE '%advanced electric machine%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'civica-uk-ltd-1'              WHERE trading_name ILIKE '%civica%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'lick-home-ltd'                WHERE trading_name ILIKE '%lick home%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'joinblink'                    WHERE trading_name ILIKE '%blink%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'dicefm-careers'               WHERE trading_name ILIKE '%dice fm%' OR trading_name ILIKE '%dicefm%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'foundersforum'                WHERE trading_name ILIKE '%founders forum%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'hack-the-box-ltd'             WHERE trading_name ILIKE '%hack the box%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'itg'                          WHERE trading_name ILIKE '%itg%' AND char_length(trading_name) < 8;
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'mention-me-ltd'               WHERE trading_name ILIKE '%mention me%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'oakengage'                    WHERE trading_name ILIKE '%oak engage%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'raftai'                       WHERE trading_name ILIKE '%raft ai%' OR trading_name ILIKE '%raftai%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'recraft'                      WHERE trading_name ILIKE '%recraft%';
UPDATE companies SET ats_provider = 'bamboohr',       ats_board_token = 'subseacraft'                  WHERE trading_name ILIKE '%subsea craft%' OR trading_name ILIKE '%subseacraft%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'External_Career_Site_Barclays' WHERE trading_name ILIKE '%barclays%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Careers'                      WHERE trading_name ILIKE '%london stock exchange%' OR trading_name ILIKE '%lseg%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'LBG_Careers'                  WHERE trading_name ILIKE '%lloyds banking%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Diageo_Careers'               WHERE trading_name ILIKE '%diageo%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'KANTAR'                       WHERE trading_name ILIKE '%kantar%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'DarktaceExternal'             WHERE trading_name ILIKE '%darktrace%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Linklaters'                   WHERE trading_name ILIKE '%linklaters%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'External_Careers'             WHERE trading_name ILIKE '%cancer research uk%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Alphawave_External'           WHERE trading_name ILIKE '%alphawave%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Apollo_Careers'               WHERE trading_name ILIKE '%apollo%' AND (trading_name ILIKE '%athene%' OR trading_name ILIKE '%asset%' OR trading_name ILIKE '%global%');
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'AQA'                          WHERE trading_name ILIKE '%aqa%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Careers'                      WHERE trading_name ILIKE '%broadridge%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'careers'                      WHERE trading_name ILIKE '%dynata%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'HVP'                          WHERE trading_name ILIKE '%harbourvest%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'external_careers'             WHERE trading_name ILIKE '%icg%' AND trading_name NOT ILIKE '%icge%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Intapp'                       WHERE trading_name ILIKE '%intapp%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'InterDigital_Career'          WHERE trading_name ILIKE '%interdigital%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'CDPQ'                         WHERE trading_name ILIKE '%cdpq%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'LNExternalSite'               WHERE trading_name ILIKE '%live nation%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Marshall_Group'               WHERE trading_name ILIKE '%marshall group%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'nVent'                        WHERE trading_name ILIKE '%nvent%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'Railpen'                      WHERE trading_name ILIKE '%railpen%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'External_Career_Site'         WHERE trading_name ILIKE '%relativity%' OR trading_name ILIKE '%kcura%';
UPDATE companies SET ats_provider = 'oracle_cloud',   ats_board_token = 'CX_1018'                      WHERE trading_name ILIKE '%eckert seamans%';
UPDATE companies SET ats_provider = 'ashby',          ats_board_token = 'claylabs'                     WHERE trading_name ILIKE '%clay%' AND char_length(trading_name) < 8;
UPDATE companies SET ats_provider = 'rippling',       ats_board_token = '11fs-group-ltd'               WHERE trading_name ILIKE '%11fs%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = '10xbanking'                   WHERE trading_name ILIKE '%10x banking%' OR trading_name ILIKE '%10xbanking%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = '1global'                      WHERE trading_name ILIKE '%1global%';
UPDATE companies SET ats_provider = 'lever',          ats_board_token = '32Co'                         WHERE trading_name ILIKE '%32co%' OR trading_name ILIKE '%32 co%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'a24'                          WHERE trading_name ILIKE '%a24%';
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'abm-careers'                  WHERE trading_name ILIKE '%abm%' AND char_length(trading_name) < 10;
UPDATE companies SET ats_provider = 'workable',       ats_board_token = 'and-digital'                  WHERE trading_name ILIKE '%and digital%';
UPDATE companies SET ats_provider = 'smartrecruiters',ats_board_token = 'ASOS'                         WHERE trading_name ILIKE '%asos%';
UPDATE companies SET ats_provider = 'greenhouse',     ats_board_token = 'addepar1'                     WHERE trading_name ILIKE '%addepar%';
UPDATE companies SET ats_provider = 'teamtailor',     ats_board_token = 'addisonlee'                   WHERE trading_name ILIKE '%addison lee%';
UPDATE companies SET ats_provider = 'workday',        ats_board_token = 'external_experienced'         WHERE trading_name ILIKE '%adobe%';

